import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='flex gap-8'>
          <ul><Link href={'/home'}>Home</Link></ul>
          <ul><Link href={'/about'}>About</Link></ul>
        </nav>
        <hr />
        {children}
        </body>
    </html>
  )
}
